[build]
command = "pip install -r requirements.txt && python manage.py collectstatic --noinput"
publish = "staticfiles"
environment = { PYTHON_VERSION = "3.13" }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200