# Generated by Django 4.2.7 on 2025-03-01 18:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='certificates/')),
                ('date_received', models.DateField()),
                ('issuing_organization', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date_received'],
            },
        ),
    ]
