# Generated by Django 4.2.7 on 2025-03-01 18:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Content for About section', null=True),
        ),
    ]
